apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app: {{ .Release.Name }}
    component: frontend
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.frontend.NEXT_PUBLIC_API_URL | quote }}
  NEXT_PUBLIC_APP_NAME: {{ .Values.config.frontend.NEXT_PUBLIC_APP_NAME | quote }}