apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Release.Name }}
    component: postgres
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) | b64enc | quote }}