{{- $ := . }}
{{- $component := "postgres" }}
{{- $values := .Values }}

{{- $dynamicSecretData := dict
  "username" $values.auth.username
  "password" ($values.auth.password | default (randAlphaNum 16))
}}
{{- include "library.secret" (list $ $component (dict
    "secretType" "Opaque"
    "secretData" $dynamicSecretData
)) }}

{{- if $values.persistence.enabled }}
---
{{- include "library.pvc" (list $ $component $values) }}
{{- end }}

---
{{- $postgresValues := deepCopy $values }}

{{- $dynamicEnv := list
  (dict "name" "POSTGRES_DB" "value" $values.auth.database)
  (dict
    "name" "POSTGRES_USER"
    "valueFrom" (dict "secretKeyRef" (dict "name" (printf "%s-postgres-secret" $.Release.Name) "key" "username"))
  )
  (dict
    "name" "POSTGRES_PASSWORD"
    "valueFrom" (dict "secretKeyRef" (dict "name" (printf "%s-postgres-secret" $.Release.Name) "key" "password"))
  )
  (dict "name" "PGDATA" "value" "/var/lib/postgresql/data/pgdata")
}}
{{- $_ := set $postgresValues "env" $dynamicEnv }}

{{- $dynamicVolumes := list
  (dict "name" "postgres-storage" "persistentVolumeClaim" (dict "claimName" (printf "%s-postgres-pvc" $.Release.Name)))
}}
{{- $_ := set $postgresValues "volumes" $dynamicVolumes }}

{{- include "library.deployment" (list $ $component $postgresValues) }}

---
{{- include "library.service" (list $ $component $values) }}