# Production environment overrides

replicaCount: 1

# Sub-chart overrides — keys must match dependency chart names
frontend:
  enabled: true
  image:
    repository: tochratana/prod-ui
    tag: "b2518c6c"
    pullPolicy: Always
  config:
    NEXT_PUBLIC_API_URL: "/api"
    NEXT_PUBLIC_APP_NAME: "MyApp"

backend:
  enabled: true
  image:
    repository: tochratana/prod-api
    tag: "01d931c2"
    pullPolicy: Always
  config:
    SPRING_PROFILES_ACTIVE: "k8s"
    LOGGING_LEVEL_COM_EXAMPLE: "INFO"
    SERVER_PORT: "8080"
  database:
    name: appdb

postgres:
  enabled: true
  persistence:
    size: 10Gi
    storageClass: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
  hosts:
    - host: full-stack-dpl.tochratana.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 3000
        - path: /api
          pathType: Prefix
          service: backend
          port: 8080
  tls:
    - secretName: full-stack-dpl-tls
      hosts:
        - full-stack-dpl.tochratana.com