apiVersion: v2
name: postgres
description: PostgreSQL database for fullstack application
type: application
version: 0.1.0
appVersion: "15.0"

dependencies:
  - name: library
    version: 0.1.0
    repository: file://../library
