{{- define "library.secret" -}}
{{- $ := index . 0 }}
{{- $component := index . 1 }}
{{- $values := index . 2 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-secret" $.Release.Name $component }}
  labels:
    {{- include "library.commonLabels" (list $ $component) | nindent 4 }}
type: {{ $values.secretType | default "Opaque" }}
data:
  {{- range $key, $value := $values.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}