frontend:
  image:
    tag: dev-latest
  config:
    NEXT_PUBLIC_APP_NAME: "MyApp (Dev)"
  
backend:
  image:
    tag: dev-latest
  config:
    LOGGING_LEVEL_COM_EXAMPLE: DEBUG

postgres:
  persistence:
    size: 5Gi

ingress:
  hosts:
    - host: full-stack-dpl.tochratana.com